
import { CurriculumTheme, CurriculumTopic, GradeLevel } from "./types";

export const THEMES: CurriculumTheme[] = [
  // --- VI ОДДЕЛЕНИЕ ТЕМИ ---
  { id: "vi-theme-1", title: "Тема 1: БРОЕВИ", grade: GradeLevel.VI },
  { id: "vi-theme-2", title: "Тема 2: ГЕОМЕТРИЈА", grade: GradeLevel.VI },
  { id: "vi-theme-3", title: "Тема 3: ОПЕРАЦИИ СО БРОЕВИ", grade: GradeLevel.VI },
  { id: "vi-theme-4", title: "Тема 4: МЕРЕЊЕ", grade: GradeLevel.VI },
  { id: "vi-theme-5", title: "Тема 5: РАБОТА СО ПОДАТОЦИ", grade: GradeLevel.VI },

  // --- VII ОДДЕЛЕНИЕ ТЕМИ ---
  { id: "theme-1", title: "Тема 1: БРОЕВИ И ОПЕРАЦИИ СО БРОЕВИ", grade: GradeLevel.VII },
  { id: "theme-2", title: "Тема 2: ГЕОМЕТРИЈА", grade: GradeLevel.VII },
  { id: "theme-3", title: "Тема 3: АЛГЕБРА", grade: GradeLevel.VII },
  { id: "theme-4", title: "Тема 4: МЕРЕЊЕ", grade: GradeLevel.VII },
  { id: "theme-5", title: "Тема 5: РАБОТА СО ПОДАТОЦИ", grade: GradeLevel.VII },
];

export const CURRICULUM: CurriculumTopic[] = [
  // ==========================================
  // VI ОДДЕЛЕНИЕ (6th Grade)
  // ==========================================
  
  // --- ТЕМА 1: БРОЕВИ (VI) ---
  { id: "vi-1.1", themeId: "vi-theme-1", name: "1.1. Множество", grade: GradeLevel.VI },
  { id: "vi-1.2", themeId: "vi-theme-1", name: "1.2. Запишување множества", grade: GradeLevel.VI },
  { id: "vi-1.3", themeId: "vi-theme-1", name: "1.3. Симболите ∈ и ∉. Празно множество", grade: GradeLevel.VI },
  { id: "vi-1.4", themeId: "vi-theme-1", name: "1.4. Број на елементи на множество", grade: GradeLevel.VI },
  { id: "vi-1.5", themeId: "vi-theme-1", name: "1.5. Подмножество", grade: GradeLevel.VI },
  { id: "vi-1.6", themeId: "vi-theme-1", name: "1.6. Конечни и бесконечни множества", grade: GradeLevel.VI },
  { id: "vi-1.7", themeId: "vi-theme-1", name: "1.7. Множеството на природни броеви", grade: GradeLevel.VI },
  { id: "vi-1.8", themeId: "vi-theme-1", name: "1.8. Природни броеви на бројна права", grade: GradeLevel.VI },
  { id: "vi-1.9", themeId: "vi-theme-1", name: "1.9. Класи и месна вредност", grade: GradeLevel.VI },
  { id: "vi-1.10", themeId: "vi-theme-1", name: "1.10. Споредување и подредување природни броеви", grade: GradeLevel.VI },
  { id: "vi-1.11", themeId: "vi-theme-1", name: "1.11. Заокружување природни броеви", grade: GradeLevel.VI },
  { id: "vi-1.12", themeId: "vi-theme-1", name: "1.12. Низа на природни броеви", grade: GradeLevel.VI },
  { id: "vi-1.13", themeId: "vi-theme-1", name: "1.13. Пишување броеви со римски цифри", grade: GradeLevel.VI },
  { id: "vi-1.14", themeId: "vi-theme-1", name: "1.14. Множество цели броеви", grade: GradeLevel.VI },
  { id: "vi-1.15", themeId: "vi-theme-1", name: "1.15. Цели броеви на бројна права", grade: GradeLevel.VI },
  { id: "vi-1.16", themeId: "vi-theme-1", name: "1.16. Споредување и подредување цели броеви", grade: GradeLevel.VI },
  { id: "vi-1.17", themeId: "vi-theme-1", name: "1.17. Низи од цели броеви", grade: GradeLevel.VI },
  { id: "vi-1.18", themeId: "vi-theme-1", name: "1.18. Низи од дропки", grade: GradeLevel.VI },
  { id: "vi-1.19", themeId: "vi-theme-1", name: "1.19. Запишување неправилна дропка како мешан број и обратно", grade: GradeLevel.VI },
  { id: "vi-1.20", themeId: "vi-theme-1", name: "1.20. Месна вредност на цифри во децимален број", grade: GradeLevel.VI },
  { id: "vi-1.21", themeId: "vi-theme-1", name: "1.21. Низи од децимални броеви", grade: GradeLevel.VI },
  { id: "vi-1.22", themeId: "vi-theme-1", name: "1.22. Заокружување децимални броеви", grade: GradeLevel.VI },
  { id: "vi-1.23", themeId: "vi-theme-1", name: "1.23. Проширување и скратување дропки", grade: GradeLevel.VI },
  { id: "vi-1.24", themeId: "vi-theme-1", name: "1.24. Претставување мешани броеви на бројна права", grade: GradeLevel.VI },
  { id: "vi-1.25", themeId: "vi-theme-1", name: "1.25. Споредување дропки", grade: GradeLevel.VI },
  { id: "vi-1.26", themeId: "vi-theme-1", name: "1.26. Споредување децимални броеви", grade: GradeLevel.VI },
  { id: "vi-1.27", themeId: "vi-theme-1", name: "1.27. Проценти", grade: GradeLevel.VI },
  { id: "vi-1.28", themeId: "vi-theme-1", name: "1.28. Размер", grade: GradeLevel.VI },

  // --- ТЕМА 2: ГЕОМЕТРИЈА (VI) ---
  { id: "vi-2.1", themeId: "vi-theme-2", name: "2.1. Права. Отсечка", grade: GradeLevel.VI },
  { id: "vi-2.2", themeId: "vi-theme-2", name: "2.2. Собирање и одземање должини на отсечки", grade: GradeLevel.VI },
  { id: "vi-2.3", themeId: "vi-theme-2", name: "2.3. Заемно нормални и заемно паралелни прави", grade: GradeLevel.VI },
  { id: "vi-2.4", themeId: "vi-theme-2", name: "2.4. Растојание од точка до права", grade: GradeLevel.VI },
  { id: "vi-2.5", themeId: "vi-theme-2", name: "2.5. Симетрала на отсечка", grade: GradeLevel.VI },
  { id: "vi-2.6", themeId: "vi-theme-2", name: "2.6. Агол", grade: GradeLevel.VI },
  { id: "vi-2.7", themeId: "vi-theme-2", name: "2.7. Соседни, напоредни и накрсни агли", grade: GradeLevel.VI },
  { id: "vi-2.8", themeId: "vi-theme-2", name: "2.8. Мерење агли", grade: GradeLevel.VI },
  { id: "vi-2.9", themeId: "vi-theme-2", name: "2.9. Комплементни и суплементни агли", grade: GradeLevel.VI },
  { id: "vi-2.10", themeId: "vi-theme-2", name: "2.10. Симетрала на агол", grade: GradeLevel.VI },
  { id: "vi-2.11", themeId: "vi-theme-2", name: "2.11. Кружница. Круг", grade: GradeLevel.VI },
  { id: "vi-2.12", themeId: "vi-theme-2", name: "2.12. Заемна положба на точка и кружница и права и кружница", grade: GradeLevel.VI },
  { id: "vi-2.13", themeId: "vi-theme-2", name: "2.13. Заемна положба на две кружници", grade: GradeLevel.VI },
  { id: "vi-2.14", themeId: "vi-theme-2", name: "2.14. Многуаголници", grade: GradeLevel.VI },
  { id: "vi-2.15", themeId: "vi-theme-2", name: "2.15. Дијагонали на многуаголник", grade: GradeLevel.VI },
  { id: "vi-2.16", themeId: "vi-theme-2", name: "2.16. Висина на триаголник. Ортоцентар", grade: GradeLevel.VI },
  { id: "vi-2.17", themeId: "vi-theme-2", name: "2.17. Тежишна линија во триаголник. Тежиште", grade: GradeLevel.VI },
  { id: "vi-2.18", themeId: "vi-theme-2", name: "2.18. Опишана кружница кај триаголник", grade: GradeLevel.VI },
  { id: "vi-2.19", themeId: "vi-theme-2", name: "2.19. Впишана кружница во триаголник", grade: GradeLevel.VI },
  { id: "vi-2.20", themeId: "vi-theme-2", name: "2.20. Однос на страните и аглите во триаголник", grade: GradeLevel.VI },
  { id: "vi-2.21", themeId: "vi-theme-2", name: "2.21. Збир на агли во триаголник", grade: GradeLevel.VI },
  { id: "vi-2.22", themeId: "vi-theme-2", name: "2.22. Врска меѓу 2Д- и 3Д-форми", grade: GradeLevel.VI },
  { id: "vi-2.23", themeId: "vi-theme-2", name: "2.23. Мрежи на призма и пирамида", grade: GradeLevel.VI },
  { id: "vi-2.24", themeId: "vi-theme-2", name: "2.24. Мрежа на цилиндар", grade: GradeLevel.VI },
  { id: "vi-2.25", themeId: "vi-theme-2", name: "2.25. Правоаголен координатен систем", grade: GradeLevel.VI },
  { id: "vi-2.26", themeId: "vi-theme-2", name: "2.26. Оска симетрија во однос на координатни оски", grade: GradeLevel.VI },
  { id: "vi-2.27", themeId: "vi-theme-2", name: "2.27. Оска симетрија во однос на прави паралелни на координатните оски", grade: GradeLevel.VI },
  { id: "vi-2.28", themeId: "vi-theme-2", name: "2.28. Транслација", grade: GradeLevel.VI },
  { id: "vi-2.29", themeId: "vi-theme-2", name: "2.29. Ротација", grade: GradeLevel.VI },

  // --- ТЕМА 3: ОПЕРАЦИИ СО БРОЕВИ (VI) ---
  { id: "vi-3.1", themeId: "vi-theme-3", name: "3.1. Собирање и одземање броеви од кои едниот е близок до најблиската 10, 100 и 1000", grade: GradeLevel.VI },
  { id: "vi-3.2", themeId: "vi-theme-3", name: "3.2. Собирање броеви до 100000. Својства на собирањето", grade: GradeLevel.VI },
  { id: "vi-3.3", themeId: "vi-theme-3", name: "3.3. Одземање броеви до 100000", grade: GradeLevel.VI },
  { id: "vi-3.4", themeId: "vi-theme-3", name: "3.4. Множење со полни десетки, полни стотки или полни илјади", grade: GradeLevel.VI },
  { id: "vi-3.5", themeId: "vi-theme-3", name: "3.5. Својства на множењето во ℕ", grade: GradeLevel.VI },
  { id: "vi-3.6", themeId: "vi-theme-3", name: "3.6. Множење броеви од кои едниот е близок до полна десетка или стотка", grade: GradeLevel.VI },
  { id: "vi-3.7", themeId: "vi-theme-3", name: "3.7. Множење со удвојување или преполовување на множителите", grade: GradeLevel.VI },
  { id: "vi-3.8", themeId: "vi-theme-3", name: "3.8. Множење на двоцифрен, трицифрен и четирицифрен број со едноцифрен број", grade: GradeLevel.VI },
  { id: "vi-3.9", themeId: "vi-theme-3", name: "3.9. Множење на двоцифрен, трицифрен и четирицифрен број со двоцифрен број", grade: GradeLevel.VI },
  { id: "vi-3.10", themeId: "vi-theme-3", name: "3.10. Делење двоцифрен со едноцифрен број", grade: GradeLevel.VI },
  { id: "vi-3.11", themeId: "vi-theme-3", name: "3.11. Делење трицифрен со едноцифрен број", grade: GradeLevel.VI },
  { id: "vi-3.12", themeId: "vi-theme-3", name: "3.12. Делење броеви до 100000 со двоцифрен број", grade: GradeLevel.VI },
  { id: "vi-3.13", themeId: "vi-theme-3", name: "3.13. Бројни изрази", grade: GradeLevel.VI },
  { id: "vi-3.14", themeId: "vi-theme-3", name: "3.14. Решавање равенки", grade: GradeLevel.VI },
  { id: "vi-3.15", themeId: "vi-theme-3", name: "3.15. Примена на равенки во решавање проблеми", grade: GradeLevel.VI },
  { id: "vi-3.16", themeId: "vi-theme-3", name: "3.16. Делители и содржатели", grade: GradeLevel.VI },
  { id: "vi-3.17", themeId: "vi-theme-3", name: "3.17. Разложување двоцифрен број на множители", grade: GradeLevel.VI },
  { id: "vi-3.18", themeId: "vi-theme-3", name: "3.18. Прости и сложени броеви", grade: GradeLevel.VI },
  { id: "vi-3.19", themeId: "vi-theme-3", name: "3.19. Претставување сложен број како производ од прости множители", grade: GradeLevel.VI },
  { id: "vi-3.20", themeId: "vi-theme-3", name: "3.20. Признаци за деливост со 2, 5 и 10", grade: GradeLevel.VI },
  { id: "vi-3.21", themeId: "vi-theme-3", name: "3.21. Признаци за деливост со 9, 3 и 6", grade: GradeLevel.VI },
  { id: "vi-3.22", themeId: "vi-theme-3", name: "3.22. Признаци за деливост со 4 и 8", grade: GradeLevel.VI },
  { id: "vi-3.23", themeId: "vi-theme-3", name: "3.23. Заеднички делители. Најголем заеднички делител", grade: GradeLevel.VI },
  { id: "vi-3.24", themeId: "vi-theme-3", name: "3.24. Заеднички содржатели. Најмал заеднички содржател", grade: GradeLevel.VI },
  { id: "vi-3.25", themeId: "vi-theme-3", name: "3.25. Собирање и одземање на правилни дропки со еднакви именители", grade: GradeLevel.VI },
  { id: "vi-3.26", themeId: "vi-theme-3", name: "3.26. Собирање и одземање неправилни дропки", grade: GradeLevel.VI },
  { id: "vi-3.27", themeId: "vi-theme-3", name: "3.27. Парови децимални броеви со две децимали чиј збир е 1 и парови децимални броеви со една децимала чиј збир е 10", grade: GradeLevel.VI },
  { id: "vi-3.28", themeId: "vi-theme-3", name: "3.28. Собирање на децимални броеви со еднаков број децимални места", grade: GradeLevel.VI },
  { id: "vi-3.29", themeId: "vi-theme-3", name: "3.29. Одземање децимални броеви со еднаков број децимални места", grade: GradeLevel.VI },
  { id: "vi-3.30", themeId: "vi-theme-3", name: "3.30. Собирање и одземање децимални броеви од кои едниот е близок до цел број", grade: GradeLevel.VI },
  { id: "vi-3.31", themeId: "vi-theme-3", name: "3.31. Собирање и одземање на децимални броеви со различен број децимални места", grade: GradeLevel.VI },
  { id: "vi-3.32", themeId: "vi-theme-3", name: "3.32. Множење децимални броеви со природен број", grade: GradeLevel.VI },
  { id: "vi-3.33", themeId: "vi-theme-3", name: "3.33. Множење децимални броеви со децимално место", grade: GradeLevel.VI },
  { id: "vi-3.34", themeId: "vi-theme-3", name: "3.34. Делење на децимален број со една и две децимали со едноцифрен број", grade: GradeLevel.VI },

  // --- ТЕМА 4: МЕРЕЊЕ (VI) ---
  { id: "vi-4.1", themeId: "vi-theme-4", name: "4.1. Должина. Мерки за должина", grade: GradeLevel.VI },
  { id: "vi-4.2", themeId: "vi-theme-4", name: "4.2. Маса. Мерки за маса", grade: GradeLevel.VI },
  { id: "vi-4.3", themeId: "vi-theme-4", name: "4.3. Зафатнина. Мерки за зафатнина", grade: GradeLevel.VI },
  { id: "vi-4.4", themeId: "vi-theme-4", name: "4.4. Едноимени броеви. Претворање на едноимен број во друг едноимен број", grade: GradeLevel.VI },
  { id: "vi-4.5", themeId: "vi-theme-4", name: "4.5. Повеќеимени броеви. Претворање на едноимен број во повеќеимен број и обратно", grade: GradeLevel.VI },
  { id: "vi-4.6", themeId: "vi-theme-4", name: "4.6. Споредување мерења на должина, маса и зафатнина", grade: GradeLevel.VI },
  { id: "vi-4.7", themeId: "vi-theme-4", name: "4.7. Проценување должина, маса и зафатнина", grade: GradeLevel.VI },
  { id: "vi-4.8", themeId: "vi-theme-4", name: "4.8. Периметар на многуаголник", grade: GradeLevel.VI },
  { id: "vi-4.9", themeId: "vi-theme-4", name: "4.9. Време. Мерки за време", grade: GradeLevel.VI },
  { id: "vi-4.10", themeId: "vi-theme-4", name: "4.10. Дигитални и аналогни часовници", grade: GradeLevel.VI },
  { id: "vi-4.11", themeId: "vi-theme-4", name: "4.11. Споредување време", grade: GradeLevel.VI },
  { id: "vi-4.12", themeId: "vi-theme-4", name: "4.12. Временски интервали", grade: GradeLevel.VI },
  { id: "vi-4.13", themeId: "vi-theme-4", name: "4.13. Календар", grade: GradeLevel.VI },
  { id: "vi-4.14", themeId: "vi-theme-4", name: "4.14. Пари", grade: GradeLevel.VI },
  { id: "vi-4.15", themeId: "vi-theme-4", name: "4.15. Плоштина. Мерки за плоштина", grade: GradeLevel.VI },
  { id: "vi-4.16", themeId: "vi-theme-4", name: "4.16. Плоштина на форми што можат да се поделат на правоаголници", grade: GradeLevel.VI },
  { id: "vi-4.17", themeId: "vi-theme-4", name: "4.17. Плоштина на правоаголен триаголник", grade: GradeLevel.VI },
  { id: "vi-4.18", themeId: "vi-theme-4", name: "4.18. Проценување плоштина на неправилен многуаголник во квадратна мрежа", grade: GradeLevel.VI },

  // --- ТЕМА 5: РАБОТА СО ПОДАТОЦИ (VI) ---
  { id: "vi-5.1", themeId: "vi-theme-5", name: "5.1. Читање податоци од табели и дијаграми", grade: GradeLevel.VI },
  { id: "vi-5.2", themeId: "vi-theme-5", name: "5.2. Претставување податоци со табела на честота", grade: GradeLevel.VI },
  { id: "vi-5.3", themeId: "vi-theme-5", name: "5.3. Претставување податоци со линиски дијаграм", grade: GradeLevel.VI },
  { id: "vi-5.4", themeId: "vi-theme-5", name: "5.4. Претставување податоци со столбест дијаграм", grade: GradeLevel.VI },
  { id: "vi-5.5", themeId: "vi-theme-5", name: "5.5. Истражување", grade: GradeLevel.VI },
  { id: "vi-5.6", themeId: "vi-theme-5", name: "5.6. Мода. Аритметичка средина", grade: GradeLevel.VI },
  { id: "vi-5.7", themeId: "vi-theme-5", name: "5.7. Ранг. Медијана", grade: GradeLevel.VI },
  { id: "vi-5.8", themeId: "vi-theme-5", name: "5.8. Сигурен настан, невозможен настан и еднакво веројатни настани", grade: GradeLevel.VI },


  // ==========================================
  // VII ОДДЕЛЕНИЕ (7th Grade) - Existing
  // ==========================================
  
  // --- ТЕМА 1: БРОЕВИ И ОПЕРАЦИИ СО БРОЕВИ (VII) ---
  { id: "1.1", themeId: "theme-1", name: "1.1 Операции со множества", grade: GradeLevel.VII },
  { id: "1.2", themeId: "theme-1", name: "1.2 Својства на операциите пресек и унија на множества", grade: GradeLevel.VII },
  { id: "1.3", themeId: "theme-1", name: "1.3 Множество од подредени парови", grade: GradeLevel.VII },
  { id: "1.4", themeId: "theme-1", name: "1.4 Декартов производ и декартова шема", grade: GradeLevel.VII },
  { id: "1.5", themeId: "theme-1", name: "1.5 Цели броеви подредување и споредување", grade: GradeLevel.VII },
  { id: "1.6", themeId: "theme-1", name: "1.6 Апсолутна вредност", grade: GradeLevel.VII },
  { id: "1.7", themeId: "theme-1", name: "1.7 Собирање цели броеви со исти или различни знаци", grade: GradeLevel.VII },
  { id: "1.8", themeId: "theme-1", name: "1.8 Својства на собирањето цели броеви", grade: GradeLevel.VII },
  { id: "1.9", themeId: "theme-1", name: "1.9 Одземање цели броеви", grade: GradeLevel.VII },
  { id: "1.10", themeId: "theme-1", name: "1.10 Множење цели броеви", grade: GradeLevel.VII },
  { id: "1.11", themeId: "theme-1", name: "1.11 Делење цели броеви", grade: GradeLevel.VII },
  { id: "1.12", themeId: "theme-1", name: "1.12 Вредност на броен израз", grade: GradeLevel.VII },
  { id: "1.13", themeId: "theme-1", name: "1.13 Степен со показател природен број", grade: GradeLevel.VII },
  { id: "1.14", themeId: "theme-1", name: "1.14 Квадрати и квадратни корени на природни броеви до 100", grade: GradeLevel.VII },
  { id: "1.15", themeId: "theme-1", name: "1.15 Подредување и споредување дропки", grade: GradeLevel.VII },
  { id: "1.16", themeId: "theme-1", name: "1.16 Децимални броеви, периодични децимални броеви", grade: GradeLevel.VII },
  { id: "1.17", themeId: "theme-1", name: "1.17 Опишување, пресметување и споредување делови од целината со дропки и проценти", grade: GradeLevel.VII },
  { id: "1.18", themeId: "theme-1", name: "1.18 Проблеми со проценти", grade: GradeLevel.VII },
  { id: "1.19", themeId: "theme-1", name: "1.19 Собирање и одземање дропки", grade: GradeLevel.VII },
  { id: "1.20", themeId: "theme-1", name: "1.20 Множење дропки", grade: GradeLevel.VII },
  { id: "1.21", themeId: "theme-1", name: "1.21 Делење дропки", grade: GradeLevel.VII },
  { id: "1.22", themeId: "theme-1", name: "1.22 Проблеми со дропки", grade: GradeLevel.VII },
  { id: "1.23", themeId: "theme-1", name: "1.23 Собирање и одземање децимални броеви", grade: GradeLevel.VII },
  { id: "1.24", themeId: "theme-1", name: "1.24 Множење и делење децимални броеви", grade: GradeLevel.VII },
  { id: "1.25", themeId: "theme-1", name: "1.25 Размер", grade: GradeLevel.VII },
  { id: "1.26", themeId: "theme-1", name: "1.26 Правопропорционалност", grade: GradeLevel.VII },

  // --- ТЕМА 2: ГЕОМЕТРИЈА (VII) ---
  { id: "2.1", themeId: "theme-2", name: "2.1 Кружница, круг, кружен лак", grade: GradeLevel.VII },
  { id: "2.2", themeId: "theme-2", name: "2.2 Заемнa положбa на точка,права и кружница со кружница. Тангента на кружница", grade: GradeLevel.VII },
  { id: "2.3", themeId: "theme-2", name: "2.3 Колинеарни и неколинеарни точки", grade: GradeLevel.VII },
  { id: "2.4", themeId: "theme-2", name: "2.4 Графичко собирање и одземање отсечки", grade: GradeLevel.VII },
  { id: "2.5", themeId: "theme-2", name: "2.5 Конструкција на паралелни и нормални прави", grade: GradeLevel.VII },
  { id: "2.6", themeId: "theme-2", name: "2.6 Симетрала на отсечка", grade: GradeLevel.VII },
  { id: "2.7", themeId: "theme-2", name: "2.7 Основни конструкции со образовниот софтвер геогебра", grade: GradeLevel.VII },
  { id: "2.8", themeId: "theme-2", name: "2.8 Основни поими за агли и полурамнини", grade: GradeLevel.VII },
  { id: "2.9", themeId: "theme-2", name: "2.9 Мерење, проценување и цртање агли", grade: GradeLevel.VII },
  { id: "2.10", themeId: "theme-2", name: "2.10 Централен агол", grade: GradeLevel.VII },
  { id: "2.11", themeId: "theme-2", name: "2.11 Аритметички операции со агли", grade: GradeLevel.VII },
  { id: "2.12", themeId: "theme-2", name: "2.12 Графичко собирање и одземање агли", grade: GradeLevel.VII },
  { id: "2.13", themeId: "theme-2", name: "2.13 Симетрала на агол конструкција на агли од 60°, 30°, 15°, 90°, 45°", grade: GradeLevel.VII },
  { id: "2.14", themeId: "theme-2", name: "2.14 Конструкција на симетрала на агол и агли со помош на образовниот софтвер геогебра", grade: GradeLevel.VII },
  { id: "2.15", themeId: "theme-2", name: "2.15 Агли на трансверзала", grade: GradeLevel.VII },
  { id: "2.16", themeId: "theme-2", name: "2.16 Конвексни и неконвексни многуаголници", grade: GradeLevel.VII },
  { id: "2.17", themeId: "theme-2", name: "2.17 Решавање проблеми од триаголник (средна линија, ортоцентар, тежиште...)", grade: GradeLevel.VII },
  { id: "2.18", themeId: "theme-2", name: "2.18 Конструкција на триаголник", grade: GradeLevel.VII },
  { id: "2.19", themeId: "theme-2", name: "2.19 Конструкција на опишана кружница", grade: GradeLevel.VII },
  { id: "2.20", themeId: "theme-2", name: "2.20 Конструкција на впишана кружница", grade: GradeLevel.VII },
  { id: "2.21", themeId: "theme-2", name: "2.21 Конструкција на триаголник со образовниот софтвер геогебра", grade: GradeLevel.VII },
  { id: "2.22", themeId: "theme-2", name: "2.22 Конструкција на опишана и впишана кружница со софтвер геогебра", grade: GradeLevel.VII },
  { id: "2.23", themeId: "theme-2", name: "2.23 Четириаголници и класификација според паралелност на страните", grade: GradeLevel.VII },
  { id: "2.24", themeId: "theme-2", name: "2.24 Висини и дијагонали на паралелограм", grade: GradeLevel.VII },
  { id: "2.25", themeId: "theme-2", name: "2.25 Решавање проблеми со својства на паралелограм", grade: GradeLevel.VII },
  { id: "2.26", themeId: "theme-2", name: "2.26 Збир на агли во четириаголник", grade: GradeLevel.VII },
  { id: "2.27", themeId: "theme-2", name: "2.27 Осна симетрија и транслација", grade: GradeLevel.VII },
  { id: "2.28", themeId: "theme-2", name: "2.28 Ротација", grade: GradeLevel.VII },
  { id: "2.29", themeId: "theme-2", name: "2.29 Проблеми со осна симетрија, транслација и ротација", grade: GradeLevel.VII },
  { id: "2.30", themeId: "theme-2", name: "2.30 Проекции на 3д форми", grade: GradeLevel.VII },

  // --- ТЕМА 3: АЛГЕБРА (VII) ---
  { id: "3.1", themeId: "theme-3", name: "3.1 Членови, изрази и равенки", grade: GradeLevel.VII },
  { id: "3.2", themeId: "theme-3", name: "3.2 Упростување линеарен израз", grade: GradeLevel.VII },
  { id: "3.3", themeId: "theme-3", name: "3.3 Пресметување вредност на линеарен израз", grade: GradeLevel.VII },
  { id: "3.4", themeId: "theme-3", name: "3.4 Формули за изразување на една променлива преку друга", grade: GradeLevel.VII },
  { id: "3.5", themeId: "theme-3", name: "3.5 Линеарна равенка со една непозната решение на равенка", grade: GradeLevel.VII },
  { id: "3.6", themeId: "theme-3", name: "3.6 Низи од цели броеви", grade: GradeLevel.VII },
  { id: "3.7", themeId: "theme-3", name: "3.7 Низи од визуелни прикази. општ член во низа", grade: GradeLevel.VII },
  { id: "3.8", themeId: "theme-3", name: "3.8 Претставување едноставни функции", grade: GradeLevel.VII },
  { id: "3.9", themeId: "theme-3", name: "3.9 Графички приказ на линеарна функција. функции парелелни со x или y оска", grade: GradeLevel.VII },

  // --- ТЕМА 4: МЕРЕЊЕ (VII) ---
  { id: "4.1", themeId: "theme-4", name: "4.1 Мерни единици и мерни инструменти за должина", grade: GradeLevel.VII },
  { id: "4.2", themeId: "theme-4", name: "4.2 Мерни единици и мерни инструменти за маса", grade: GradeLevel.VII },
  { id: "4.3", themeId: "theme-4", name: "4.3 Мерни единици и мерни инструменти за зафатнина", grade: GradeLevel.VII },
  { id: "4.4", themeId: "theme-4", name: "4.4 Време. 12-часовен и 24-часовен систем", grade: GradeLevel.VII },
  { id: "4.5", themeId: "theme-4", name: "4.5 Пресметување временски интервали и работа со графици", grade: GradeLevel.VII },
  { id: "4.6", themeId: "theme-4", name: "4.6 Периметар на триаголник и четириаголник", grade: GradeLevel.VII },
  { id: "4.7", themeId: "theme-4", name: "4.7 Мерни единици за плоштина", grade: GradeLevel.VII },
  { id: "4.8", themeId: "theme-4", name: "4.8 Плоштина на сложени 2д форми", grade: GradeLevel.VII },
  { id: "4.9", themeId: "theme-4", name: "4.9 Волумен и мерни единици за волумен", grade: GradeLevel.VII },
  { id: "4.10", themeId: "theme-4", name: "4.10 Волумен на квадар и коцка", grade: GradeLevel.VII },
  { id: "4.11", themeId: "theme-4", name: "4.11 Плоштина на квадар и коцка од нивните мрежи", grade: GradeLevel.VII },

  // --- ТЕМА 5: РАБОТА СО ПОДАТОЦИ (VII) ---
  { id: "5.1", themeId: "theme-5", name: "5.1 Планирање на истражување", grade: GradeLevel.VII },
  { id: "5.2", themeId: "theme-5", name: "5.2 Собирање и организирање на податоци за истражување", grade: GradeLevel.VII },
  { id: "5.3", themeId: "theme-5", name: "5.3 Столбест и кружен дијаграм", grade: GradeLevel.VII },
  { id: "5.4", themeId: "theme-5", name: "5.4 Цртање и толкување на линиски дијаграм и пиктограм", grade: GradeLevel.VII },
  { id: "5.5", themeId: "theme-5", name: "5.5 Модална класа и дијаграм на фреквенција за групирани податоци", grade: GradeLevel.VII },
  { id: "5.6", themeId: "theme-5", name: "5.6 Процена и пресметка на аритметичка средина", grade: GradeLevel.VII },
  { id: "5.7", themeId: "theme-5", name: "5.7 Веројатност", grade: GradeLevel.VII },
  { id: "5.8", themeId: "theme-5", name: "5.8 Експериментална и теоретска веројатност", grade: GradeLevel.VII },
];

export const SYSTEM_PERSONA = `
Ти си "Мате-Ментор", специјализиран асистент за математика за VI и VII одделение во Македонија.
Твојата цел е да им помогнеш на учениците и наставниците со целокупната програма.

Придржувај се до следните принципи:
1. Користи едноставен јазик соодветен за 11-13 годишни деца.
2. Давај многу визуелни описи или примери од секојдневието.
3. Биди охрабрувачки.
`;
